<script setup lang="ts">
import { computed, nextTick, onUpdated, ref } from 'vue'
import Modal from '../../lib/components/Modal.vue'
import FeatherIcon from '../FeatherIcon.vue'
import V2ProjectSettingsPanel from './V2ProjectSettingsPanel.vue'
import { useSortable, type SortableEventLike } from '../../composables/useSortable'
import { COLOR_SCHEMES, SETTINGS_NAVIGATION, V2_DASHBOARD_SECTION_OPTIONS, V2_STAGE_OPTIONS, useSettingsStore, type SettingsPanel } from '../../stores/useSettingsStore'
import { SMART_CARD_ACTION_TARGETS, normalizeSmartCardActionTarget } from '../../../lib/appSettingsSchema.js'
import type { SmartCardAction } from '../../types'

const settings = useSettingsStore()
const actionList = ref<HTMLElement | null>(null)
const labelDrafts = ref<Record<string, string>>({})
const currentScheme = computed(() => COLOR_SCHEMES.find((scheme) => scheme.id === settings.boardSettings?.colorScheme) || COLOR_SCHEMES[0]!)
const v2Sections = computed(() => Array.isArray(settings.v2Profile.dashboard?.sections) ? settings.v2Profile.dashboard.sections : V2_DASHBOARD_SECTION_OPTIONS.map((section) => section.id))
const v2CardDisplay = computed(() => settings.v2Profile.cardDisplay || {})
const groupedNavigation = computed(() => SETTINGS_NAVIGATION.reduce<Array<{ group: string; items: typeof SETTINGS_NAVIGATION[number][] }>>((groups, item) => { const group = groups.find((candidate) => candidate.group === item.group); if (group) group.items.push(item); else groups.push({ group: item.group, items: [item] }); return groups }, []))

const sortable = useSortable(actionList, { kind: 'settings', draggable: '.board-settings-ai-action[data-action-id]', group: 'smart-actions', onEnd: reorderActions })
onUpdated(() => { if (settings.isOpen && !sortable.instance) sortable.initialize(); if (!settings.isOpen && sortable.instance) sortable.destroy() })

async function reorderActions(event: SortableEventLike) {
  if (!event.to) return
  const ids = [...event.to.querySelectorAll<HTMLElement>('.board-settings-ai-action[data-action-id]')].map((element) => element.dataset.actionId || '').filter(Boolean)
  await settings.reorderActions(ids)
}

function selectPanel(panel: SettingsPanel) { settings.selectPanel(panel) }
function navId(panel: SettingsPanel) { return panel === 'app' ? 'App' : panel === 'smart-actions' ? 'SmartActions' : `${panel[0]!.toUpperCase()}${panel.slice(1)}` }
function moveNav(event: KeyboardEvent, panel: SettingsPanel) {
  const keys = ['ArrowDown', 'ArrowRight', 'ArrowUp', 'ArrowLeft', 'Home', 'End']
  if (!keys.includes(event.key)) return
  event.preventDefault(); event.stopPropagation()
  const current = SETTINGS_NAVIGATION.findIndex((item) => item.id === panel)
  const next = event.key === 'Home' ? 0 : event.key === 'End' ? SETTINGS_NAVIGATION.length - 1 : current + (event.key === 'ArrowUp' || event.key === 'ArrowLeft' ? -1 : 1)
  const item = SETTINGS_NAVIGATION[(next + SETTINGS_NAVIGATION.length) % SETTINGS_NAVIGATION.length]!
  settings.selectPanel(item.id); void nextTick(() => document.getElementById(`boardSettingsNav${navId(item.id)}`)?.focus())
}

function actionTargetLabel(action: SmartCardAction) { return action.id === 'quick-smart-action' ? 'Built in - One-off' : action.id === 'question-card' ? 'Built in - Read-only' : `${action.builtIn ? 'Built in' : 'Custom'} - ${action.target === 'title' ? 'Title' : action.target === 'labels' ? 'Labels' : action.target === 'due' ? 'Due Dates' : action.target === 'attachments' ? 'Attachments' : 'Content'}` }
function modelLabel(model: { name: string; details?: Record<string, unknown> }) { const parameterSize = typeof model.details?.parameter_size === 'string' ? model.details.parameter_size : ''; return parameterSize ? `${model.name} (${parameterSize})` : model.name }
function labelValue(id: string, value: string) { labelDrafts.value[id] = value; void settings.updateLabel(id, { name: value }) }
async function moveBoard() { const selection = await window.chooser.pickDirectory?.({ defaultPath: settings.boardPath.replace(/\/+$/, '').split('/').slice(0, -1).join('/') }); if (selection) await settings.moveBoard(selection) }
async function duplicateBoard() { const input = document.getElementById('boardSettingsDuplicateNameInput') as HTMLInputElement | null; const selection = await window.chooser.pickDirectory?.({ defaultPath: settings.boardPath.replace(/\/+$/, '').split('/').slice(0, -1).join('/') }); if (selection && typeof selection !== 'string') await settings.duplicateBoard(input?.value || `${settings.boardName} Copy`, selection) }
function labelColor(label: { id: string; colorLight?: string }, event: Event) { void settings.updateLabel(label.id, { colorLight: (event.target as HTMLInputElement).value, colorDark: (event.target as HTMLInputElement).value }) }
function actionValue(action: SmartCardAction, field: 'label' | 'target' | 'prompt', event: Event) { const value = (event.target as HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement).value; void settings.updateAction(action.id, { [field]: value }) }
function workflowChecked(listName: string) { return settings.isCompletedList(listName) }
function v2SectionEnabled(id: string) { return v2Sections.value.includes(id) }
async function toggleV2Section(id: string, enabled: boolean) {
  const next = enabled ? [...v2Sections.value, id] : v2Sections.value.filter((section) => section !== id)
  await settings.setV2DashboardSections(next)
}
async function moveV2Section(id: string, direction: -1 | 1) {
  const current = [...v2Sections.value]
  const index = current.indexOf(id)
  const target = index + direction
  if (index < 0 || target < 0 || target >= current.length) return
  const [section] = current.splice(index, 1)
  if (section) current.splice(target, 0, section)
  await settings.setV2DashboardSections(current)
}
function v2StageList(stage: string) { const value = settings.v2Profile.stages?.[stage] ; return Array.isArray(value) ? String(value[0] || '') : '' }
function v2StageLabel(stage: string) { return V2_STAGE_OPTIONS.find((option) => option.id === stage)?.label || stage }
function v2SectionLabel(id: string) { return V2_DASHBOARD_SECTION_OPTIONS.find((option) => option.id === id)?.label || id }
function copyCalendarUrl() { if (settings.externalCalendarStatus.url) void window.electronAPI.copyTextToClipboard?.(settings.externalCalendarStatus.url) }
function renameBoardFromInput() { const input = document.getElementById('boardSettingsBoardNameInput') as HTMLInputElement | null; if (input) void settings.renameBoard(input.value) }
</script>

<template>
  <Modal id="modalBoardSettings" :is-open="settings.isOpen" :on-close="settings.close" positioning="fixed" :show-chrome="false" modal-class="board-settings-modal" labelled-by="boardSettingsTitle" :initial-focus="`#boardSettingsNav${navId(settings.activePanel)}`">
    <div class="boardSettingsHeader"><h2 id="boardSettingsTitle">Settings</h2><button id="boardSettingsClose" type="button" class="board-settings-close-button" title="Close settings" aria-label="Close settings" @click="settings.close"><FeatherIcon name="x" /></button></div>
    <div class="board-settings-layout">
      <nav class="board-settings-nav" role="tablist" aria-orientation="vertical" aria-label="Settings sections">
        <template v-for="group in groupedNavigation" :key="group.group">
          <p class="board-settings-nav-label">{{ group.group }}</p>
          <button v-for="item in group.items" :id="`boardSettingsNav${navId(item.id)}`" :key="item.id" class="board-settings-nav-button" :class="{ 'is-active': settings.activePanel === item.id }" type="button" role="tab" :aria-selected="settings.activePanel === item.id ? 'true' : 'false'" :aria-controls="`boardSettingsPanel${navId(item.id)}`" :data-settings-panel="item.id" @click="selectPanel(item.id)" @keydown="moveNav($event, item.id)">{{ item.label }}</button>
          <div v-if="group.group === 'App Settings'" class="board-settings-nav-separator" role="separator" />
        </template>
      </nav>

      <div class="board-settings-panels">
        <V2ProjectSettingsPanel />
        <section id="boardSettingsPanelApp" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'app' }" role="tabpanel" :aria-hidden="settings.activePanel === 'app' ? 'false' : 'true'" aria-labelledby="boardSettingsNavApp" data-settings-panel="app">
          <h3>General</h3>
          <div class="board-settings-group"><div class="board-settings-toggle-row"><div><p class="boardSettingsHint boardSettingsHintTight">Tooltips</p><p class="boardSettingsHint">Show button and control hints throughout Signboard.</p></div><label class="board-settings-switch" for="boardSettingsTooltipsToggle" title="Enable tooltips"><input id="boardSettingsTooltipsToggle" type="checkbox" role="switch" aria-label="Enable tooltips" :checked="settings.appSettings.tooltipsEnabled" @change="settings.setTooltipsEnabled(($event.target as HTMLInputElement).checked)"><span class="board-settings-switch-track" aria-hidden="true" /></label></div></div>
          <div class="board-settings-group"><label for="boardSettingsQuickAddShortcut">Global Quick Add shortcut</label><div class="board-settings-inline-actions"><input id="boardSettingsQuickAddShortcut" type="text" placeholder="CommandOrControl+Shift+Space" spellcheck="false" autocomplete="off" :value="settings.appSettings.quickAdd.globalShortcut" @change="settings.setQuickAddShortcut(($event.target as HTMLInputElement).value)"><span id="boardSettingsQuickAddShortcutStatus" class="board-settings-status">{{ !settings.appSettings.quickAdd.globalShortcut ? 'Disabled' : settings.globalShortcutStatus.message || (settings.globalShortcutStatus.registered ? 'Registered' : 'Saved') }}</span></div><p class="boardSettingsHint">Leave blank to disable. Signboard must be open.</p></div>
        </section>

        <section id="boardSettingsPanelNotifications" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'notifications' }" role="tabpanel" :aria-hidden="settings.activePanel === 'notifications' ? 'false' : 'true'" aria-labelledby="boardSettingsNavNotifications" data-settings-panel="notifications">
          <h3>Notifications</h3>
          <div class="board-settings-group"><div class="board-settings-toggle-row"><div><p class="boardSettingsHint boardSettingsHintTight">Daily due date reminders</p><p class="boardSettingsHint">Signboard checks open boards each day at your selected local time.</p></div><label class="board-settings-switch" for="boardSettingsNotificationsToggle" title="Enable due date notifications"><input id="boardSettingsNotificationsToggle" type="checkbox" role="switch" aria-label="Enable due date notifications" :checked="settings.appSettings.notifications.enabled" @change="settings.setNotifications({ enabled: ($event.target as HTMLInputElement).checked })"><span class="board-settings-switch-track" aria-hidden="true" /></label></div></div>
          <div id="boardSettingsNotificationsDetails" class="board-settings-group" :class="{ hidden: !settings.appSettings.notifications.enabled }" :aria-hidden="settings.appSettings.notifications.enabled ? 'false' : 'true'"><label for="boardSettingsNotificationsTime">Notification time (local)</label><input id="boardSettingsNotificationsTime" type="text" placeholder="HH:MM" inputmode="numeric" maxlength="5" :value="settings.appSettings.notifications.time" @change="settings.setNotifications({ time: ($event.target as HTMLInputElement).value })"><p class="boardSettingsHint">Use HH:MM in 24-hour format. Hours can be 01 through 24.</p></div>
          <div class="board-settings-group"><div class="board-settings-toggle-row"><div><p class="boardSettingsHint boardSettingsHintTight">External Published Calendar</p><p class="boardSettingsHint">Publish a read-only local iCalendar feed while Signboard is open.</p></div><label class="board-settings-switch" for="boardSettingsExternalCalendarToggle" title="Enable External Published Calendar"><input id="boardSettingsExternalCalendarToggle" type="checkbox" role="switch" aria-label="Enable External Published Calendar" :checked="settings.appSettings.externalPublishedCalendar.enabled" @change="settings.setExternalCalendar({ enabled: ($event.target as HTMLInputElement).checked })"><span class="board-settings-switch-track" aria-hidden="true" /></label></div></div>
          <div id="boardSettingsExternalCalendarPortGroup" class="board-settings-group" :class="{ hidden: !settings.appSettings.externalPublishedCalendar.enabled }" :aria-hidden="settings.appSettings.externalPublishedCalendar.enabled ? 'false' : 'true'"><label for="boardSettingsExternalCalendarPort">Calendar feed port</label><input id="boardSettingsExternalCalendarPort" type="number" min="1024" max="65535" step="1" :value="settings.appSettings.externalPublishedCalendar.port" @change="settings.setExternalCalendar({ port: Number(($event.target as HTMLInputElement).value) })"></div>
          <div id="boardSettingsExternalCalendarUrlGroup" class="board-settings-group" :class="{ hidden: !settings.appSettings.externalPublishedCalendar.enabled }" :aria-hidden="settings.appSettings.externalPublishedCalendar.enabled ? 'false' : 'true'"><label for="boardSettingsExternalCalendarUrl">Calendar subscription URL</label><div class="board-settings-inline-actions"><input id="boardSettingsExternalCalendarUrl" type="text" readonly :value="settings.externalCalendarStatus.url"><button id="btnCopyExternalCalendarUrl" type="button" :disabled="!settings.externalCalendarStatus.url" @click="copyCalendarUrl">Copy</button><span id="boardSettingsExternalCalendarStatus" class="board-settings-status">{{ settings.externalCalendarStatus.running ? 'Publishing' : settings.appSettings.externalPublishedCalendar.enabled ? settings.externalCalendarStatus.message : 'Disabled' }}</span></div></div>
        </section>

        <section id="boardSettingsPanelSmartActions" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'smart-actions' }" role="tabpanel" :aria-hidden="settings.activePanel === 'smart-actions' ? 'false' : 'true'" aria-labelledby="boardSettingsNavSmartActions" data-settings-panel="smart-actions">
          <h3>Smart Actions</h3>
          <div class="board-settings-group"><div class="board-settings-toggle-row"><div><p class="boardSettingsHint boardSettingsHintTight">AI assistance</p><p class="boardSettingsHint">Use Ollama for local Smart Card Actions in the card editor.</p></div><label class="board-settings-switch" for="boardSettingsAiToggle" title="Enable AI assistance"><input id="boardSettingsAiToggle" type="checkbox" role="switch" aria-label="Enable AI assistance" :checked="settings.appSettings.ai.enabled" @change="settings.setAi({ enabled: ($event.target as HTMLInputElement).checked }); settings.appSettings.ai.enabled ? settings.refreshOllamaModels() : undefined"><span class="board-settings-switch-track" aria-hidden="true" /></label></div></div>
          <div id="boardSettingsAiDisabledState" class="board-settings-disabled-state" :class="{ hidden: settings.appSettings.ai.enabled }" :aria-hidden="settings.appSettings.ai.enabled ? 'true' : 'false'"><p class="boardSettingsHint boardSettingsHintTight">Smart Actions are off</p><p class="boardSettingsHint">Enable them to choose an Ollama model and customize card actions.</p></div>
          <div id="boardSettingsAiDetails" class="board-settings-group" :class="{ hidden: !settings.appSettings.ai.enabled }" :aria-hidden="settings.appSettings.ai.enabled ? 'false' : 'true'"><label for="boardSettingsAiOllamaUrl">Ollama URL</label><input id="boardSettingsAiOllamaUrl" type="url" placeholder="http://127.0.0.1:11434" :value="settings.appSettings.ai.ollama.url" @change="settings.setOllamaUrl(($event.target as HTMLInputElement).value)"><label for="boardSettingsAiOllamaModel">Ollama model</label><div class="board-settings-inline-actions board-settings-ai-model-actions"><select id="boardSettingsAiOllamaModel" aria-label="Ollama model" :value="settings.appSettings.ai.ollama.model" :disabled="settings.ollamaStatus.checking" @change="settings.setOllamaModel(($event.target as HTMLSelectElement).value)"><option v-if="!settings.ollamaStatus.models.length" :value="settings.appSettings.ai.ollama.model">{{ settings.appSettings.ai.ollama.model }}</option><option v-for="model in settings.ollamaStatus.models" :key="model.name" :value="model.name">{{ modelLabel(model) }}</option></select><button id="btnRefreshAiOllamaModels" type="button" :disabled="settings.ollamaStatus.checking" @click="settings.refreshOllamaModels">Refresh</button><span id="boardSettingsAiOllamaStatus" class="board-settings-status">{{ settings.ollamaStatus.message }}</span></div>
            <div class="board-settings-ai-actions-header"><div><p class="boardSettingsHint boardSettingsHintTight">Smart Card Actions</p><p class="boardSettingsHint">Customize prompts used by card editor AI actions.</p></div><button id="btnAddAiSmartCardAction" type="button" :disabled="settings.actions.filter((action) => !action.builtIn).length >= 12" @click="settings.addAction">Add action</button></div>
            <div id="boardSettingsAiActionsList" ref="actionList" class="board-settings-ai-actions-list"><div v-for="action in settings.actions" :key="action.id" class="board-settings-ai-action" :class="{ 'is-expanded': settings.expandedActionIds.includes(action.id) }" :data-action-id="action.id"><div class="board-settings-ai-action-header"><div class="board-settings-ai-action-title-wrap"><p class="board-settings-ai-action-title">{{ action.label }}</p><p class="board-settings-ai-action-kind">{{ actionTargetLabel(action) }}</p></div><div class="board-settings-ai-action-header-actions"><button class="board-settings-ai-action-drag-handle" type="button" :data-action-id="action.id" title="Drag to reorder action" :aria-label="`Reorder ${action.label}`" aria-keyshortcuts="ArrowUp ArrowDown" @keydown="$event.key === 'ArrowUp' || $event.key === 'ArrowDown' ? settings.moveAction(action.id, $event.key === 'ArrowUp' ? 'up' : 'down') : undefined"><FeatherIcon name="menu" /></button><button v-if="action.editable !== false" class="board-settings-ai-action-edit" type="button" :aria-expanded="settings.expandedActionIds.includes(action.id)" :aria-controls="`boardSettingsAiActionDetails-${action.id}`" @click="settings.toggleActionExpanded(action.id)">{{ settings.expandedActionIds.includes(action.id) ? 'Done' : 'Edit' }}</button><button v-if="action.builtIn && action.editable !== false" class="board-settings-ai-action-reset" type="button" @click="settings.resetAction(action.id)">Reset</button><button v-if="!action.builtIn" class="board-settings-ai-action-remove" type="button" @click="settings.removeAction(action.id)">Remove</button></div></div><div v-if="action.editable !== false" :id="`boardSettingsAiActionDetails-${action.id}`" class="board-settings-ai-action-details" :hidden="!settings.expandedActionIds.includes(action.id)" :aria-hidden="settings.expandedActionIds.includes(action.id) ? 'false' : 'true'"><template v-if="!action.builtIn"><label :for="`boardSettingsAiActionLabel-${action.id}`">Custom action label</label><input :id="`boardSettingsAiActionLabel-${action.id}`" type="text" :value="action.label" @change="actionValue(action, 'label', $event)"><label :for="`boardSettingsAiActionTarget-${action.id}`">Affects</label><select :id="`boardSettingsAiActionTarget-${action.id}`" :value="normalizeSmartCardActionTarget(action.target, 'content')" @change="actionValue(action, 'target', $event)"><option v-for="target in SMART_CARD_ACTION_TARGETS" :key="target" :value="target">{{ target }}</option></select></template><label :for="`boardSettingsAiActionPrompt-${action.id}`">{{ action.builtIn ? 'Prompt' : 'Custom action prompt' }}</label><textarea :id="`boardSettingsAiActionPrompt-${action.id}`" :rows="action.builtIn ? 4 : 5" :value="action.prompt" @change="actionValue(action, 'prompt', $event)" /></div></div></div><p class="boardSettingsHint">Card content is sent to Ollama only when you use an AI action.</p>
          </div>
        </section>

        <section id="boardSettingsPanelGeneral" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'general' }" role="tabpanel" :aria-hidden="settings.activePanel === 'general' ? 'false' : 'true'" aria-labelledby="boardSettingsNavGeneral" data-settings-panel="general"><h3>General</h3><div class="board-settings-group"><label for="boardSettingsBoardNameInput">Board name</label><div class="board-settings-inline-actions"><input id="boardSettingsBoardNameInput" type="text" :value="settings.boardName" @keydown.enter.prevent="settings.renameBoard(($event.target as HTMLInputElement).value)"><button id="btnRenameBoard" type="button" @click="renameBoardFromInput">Rename</button></div><p class="boardSettingsHint">Renaming updates this board folder name in its current location.</p></div><div class="board-settings-group"><label for="boardSettingsBoardPathInput">Current path</label><div class="board-settings-inline-actions"><input id="boardSettingsBoardPathInput" type="text" readonly :value="settings.boardPath"><button id="btnMoveBoard" type="button" @click="moveBoard">Move</button></div><p class="boardSettingsHint">Move this board folder to another location on your computer.</p></div><div class="board-settings-group"><label for="boardSettingsDuplicateNameInput">Duplicate Board name</label><div class="board-settings-inline-actions"><input id="boardSettingsDuplicateNameInput" type="text" :value="`${settings.boardName} Copy`"><button id="btnDuplicateBoard" type="button" @click="duplicateBoard">Duplicate</button></div><p class="boardSettingsHint">Duplicating a board creates a copy of all board files.</p><div id="boardSettingsDuplicateStatus" class="board-settings-status board-settings-status-inline">{{ settings.duplicateStatus }}</div></div></section>

        <section id="boardSettingsPanelLabels" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'labels' }" role="tabpanel" :aria-hidden="settings.activePanel === 'labels' ? 'false' : 'true'" aria-labelledby="boardSettingsNavLabels" data-settings-panel="labels"><h3>Labels</h3><p class="boardSettingsHint">Rename labels, choose a color, add new labels, and remove labels.</p><div id="boardSettingsLabels"><div v-for="label in settings.labels" :key="label.id" class="board-settings-label-row"><input class="board-settings-label-name" type="text" :value="labelDrafts[label.id] ?? label.name" :placeholder="label.name" @input="labelValue(label.id, ($event.target as HTMLInputElement).value)"><input class="board-settings-label-color" type="color" :value="label.colorLight || '#3b82f6'" title="Label color" @input="labelColor(label, $event)"><button class="board-settings-label-delete" type="button" title="Delete label" @click="settings.deleteLabel(label.id)"><FeatherIcon name="trash-2" /></button></div></div><button id="btnAddBoardLabel" type="button" title="Add label" @click="settings.addLabel()">Add label</button></section>

        <section id="boardSettingsPanelColors" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'colors' }" role="tabpanel" :aria-hidden="settings.activePanel === 'colors' ? 'false' : 'true'" aria-labelledby="boardSettingsNavColors" data-settings-panel="colors"><h3>Appearance</h3><p class="boardSettingsHint">Choose a color scheme for this board.</p><div class="board-color-scheme-selector"><select id="boardColorSchemeSelect" aria-label="Color scheme" :value="currentScheme.id" @change="settings.setColorScheme(($event.target as HTMLSelectElement).value)"><option v-for="scheme in COLOR_SCHEMES" :key="scheme.id" :value="scheme.id">{{ scheme.name }}</option></select></div><div class="board-theme-settings-grid"><div class="board-theme-settings-mode" :style="{ background: currentScheme.light.boardBackground, color: currentScheme.light.text, borderColor: currentScheme.light.border }"><h4>Light</h4><div id="boardThemeLightPreview" class="board-theme-preview" :style="{ background: currentScheme.light.surface, color: currentScheme.light.text, borderColor: currentScheme.light.border }">Light Preview</div></div><div class="board-theme-settings-mode" :style="{ background: currentScheme.dark.boardBackground, color: currentScheme.dark.text, borderColor: currentScheme.dark.border }"><h4>Dark</h4><div id="boardThemeDarkPreview" class="board-theme-preview" :style="{ background: currentScheme.dark.surface, color: currentScheme.dark.text, borderColor: currentScheme.dark.border }">Dark Preview</div></div></div><div class="board-theme-settings-actions"><button id="btnApplyThemeColorsToOpenBoards" type="button" @click="settings.applyColorToOpenBoards">Apply to all Open Boards</button></div></section>

        <section id="boardSettingsPanelWorkflow" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'workflow' }" role="tabpanel" :aria-hidden="settings.activePanel === 'workflow' ? 'false' : 'true'" aria-labelledby="boardSettingsNavWorkflow" data-settings-panel="workflow"><h3>Workflow</h3><p class="boardSettingsHint">Completed lists are tracked for workflow and due-date behavior.</p><div class="board-settings-group"><div class="board-settings-toggle-row"><div><p class="boardSettingsHint boardSettingsHintTight">Auto-detect completed lists</p><p class="boardSettingsHint">Done, Completed, Closed, Finished, Resolved, and Shipped lists are detected automatically.</p></div><label class="board-settings-switch" for="boardSettingsAutoDetectCompletedListsToggle"><input id="boardSettingsAutoDetectCompletedListsToggle" type="checkbox" role="switch" aria-label="Auto-detect completed lists" :checked="settings.workflow.autoDetectCompletedLists" @change="settings.setWorkflow({ autoDetectCompletedLists: ($event.target as HTMLInputElement).checked })"><span class="board-settings-switch-track" aria-hidden="true" /></label></div></div><div class="board-settings-group"><h4 class="board-settings-subheading">Completed lists</h4><div id="boardSettingsWorkflowLists" class="board-workflow-list-settings" aria-live="polite"><label v-for="listName in settings.listNames" :key="listName" class="board-workflow-list-row"><input type="checkbox" :checked="workflowChecked(listName)" @change="settings.setWorkflowList(listName, ($event.target as HTMLInputElement).checked)"><span class="board-workflow-list-content"><span class="board-workflow-list-title">{{ listName.replace(/^\d{3}-/, '').replace(/-(?:stock|[^-]{5})$/, '') }}</span><span class="board-settings-list-meta">{{ listName }}<template v-if="settings.workflow.autoDetectCompletedLists && settings.isCompletedList(listName)"> · Auto-detected</template></span></span></label><p v-if="!settings.listNames.length" class="boardSettingsHint">This board has no lists yet.</p></div></div><div class="board-settings-group"><div class="board-settings-toggle-row"><div><p class="boardSettingsHint boardSettingsHintTight">Include in External Published Calendar</p></div><label class="board-settings-switch" for="boardSettingsExternalCalendarIncludeToggle"><input id="boardSettingsExternalCalendarIncludeToggle" type="checkbox" role="switch" aria-label="Include this board in External Published Calendar" :checked="settings.boardCalendarIncluded" @change="settings.setExternalCalendarInclude(($event.target as HTMLInputElement).checked)"><span class="board-settings-switch-track" aria-hidden="true" /></label></div></div></section>

        <section id="boardSettingsPanelObsidian" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'obsidian' }" role="tabpanel" :aria-hidden="settings.activePanel === 'obsidian' ? 'false' : 'true'" aria-labelledby="boardSettingsNavObsidian" data-settings-panel="obsidian"><h3>Obsidian</h3><p class="boardSettingsHint">Keep this board inside an Obsidian vault to manage linked notes and Bases.</p><div class="board-settings-group"><h4 class="board-settings-subheading">Bases</h4><div class="board-settings-inline-actions board-settings-inline-actions-right"><button id="btnGenerateObsidianBase" type="button" @click="settings.generateBase">Generate Base</button><button id="btnOpenObsidianBase" type="button" @click="settings.openBase">Open Base</button></div><p id="boardSettingsObsidianStatus" class="boardSettingsHint" aria-live="polite">{{ settings.obsidianStatus }}</p></div></section>

        <section id="boardSettingsPanelImport" class="boardSettingsSection board-settings-panel" :class="{ 'is-active': settings.activePanel === 'import' }" role="tabpanel" :aria-hidden="settings.activePanel === 'import' ? 'false' : 'true'" aria-labelledby="boardSettingsNavImport" data-settings-panel="import"><h3>Import</h3><p class="boardSettingsHint"><strong>Note: This feature is in rapid improvement.</strong> Import data from other apps into this board.</p><div class="board-import-option"><h4>Trello</h4><button id="btnImportBoardFromTrello" type="button" :disabled="Boolean(settings.importInProgress)" @click="settings.importBoard('trello')">{{ settings.importInProgress === 'trello' ? 'Importing Trello' : 'Import from Trello' }}</button></div><div class="board-import-option"><h4>Obsidian</h4><button id="btnImportBoardFromObsidian" type="button" :disabled="Boolean(settings.importInProgress)" @click="settings.importBoard('obsidian')">{{ settings.importInProgress === 'obsidian' ? 'Importing Obsidian' : 'Import from Obsidian' }}</button></div><div class="board-import-option"><h4>Tasks.md</h4><button id="btnImportBoardFromTasksMd" type="button" :disabled="Boolean(settings.importInProgress)" @click="settings.importBoard('tasksmd')">{{ settings.importInProgress === 'tasksmd' ? 'Importing Tasks.md' : 'Import from Tasks.md' }}</button></div><div id="boardSettingsImportStatus" class="board-import-status" :class="{ hidden: !settings.importSummary }" aria-live="polite">{{ settings.summaryText(settings.importSummary) }}</div><div id="boardSettingsImportWarnings" class="board-import-warnings" :class="{ hidden: !settings.importWarnings.length }"> <p v-for="warning in settings.importWarnings" :key="warning">{{ warning }}</p></div></section>
      </div>
    </div>
  </Modal>
</template>
