<script setup lang="ts">
import { computed } from 'vue'
import { buildPlannerBuckets, formatPlannerIsoDate } from '../../../lib/planner.js'
import { usePlannerStore } from '../../stores/usePlannerStore'
import type { SortableEventLike } from '../../composables/useSortable'
import PlannerDropZone from './PlannerDropZone.vue'

const props = defineProps<{ onOpen: (entry: any) => void; onDrop: (event: SortableEventLike) => void | Promise<void> }>()
const planner = usePlannerStore()
const days = computed(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(planner.weekCursor); date.setDate(date.getDate() + index); return { iso: formatPlannerIsoDate(date), label: new Intl.DateTimeFormat(undefined, { weekday: 'long' }).format(date), short: new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(date), weekend: index >= 5 } }))
const buckets = computed(() => buildPlannerBuckets(planner.entries, (date) => days.value.some((day) => day.iso === date), { searchQuery: planner.searchQuery, dateFilter: planner.dateFilter, showCompletedCards: planner.showCompletedCards, selectedLabelIds: planner.selectedLabelIds }))
const today = computed(() => formatPlannerIsoDate(new Date()))
</script>

<template>
  <section class="planner-view planner-this-week board-this-week"><div class="board-calendar-header board-calendar-header--week planner-date-header"><div class="board-calendar-nav"><button class="board-calendar-nav-button" type="button" title="Previous week" aria-label="Previous week" @click="planner.shiftWeek(-1)">‹</button><button class="board-calendar-nav-button" type="button" title="Next week" aria-label="Next week" @click="planner.shiftWeek(1)">›</button><button class="board-calendar-today-button" type="button" title="Jump to current week" @click="planner.weekToday">Today</button></div><h2 class="board-calendar-month-label">Week of {{ days[0]?.short }} – {{ days[6]?.short }}</h2></div><div class="board-this-week-grid"><template v-for="(day, index) in days" :key="day.iso"><section v-if="index < 5" class="board-this-week-day" :class="{ 'is-today': day.iso === today, [`day-${['mon', 'tue', 'wed', 'thu', 'fri'][index]}`]: true }"><header class="board-this-week-day-header"><span class="board-this-week-day-title">{{ day.label }}</span><span class="board-this-week-day-date">{{ day.short }}</span><span v-if="day.iso === today" class="board-calendar-today-badge">Today</span></header><PlannerDropZone :date="day.iso" :entries="buckets.get(day.iso) || []" class-name="board-this-week-day-cards" group="planner-week-cards" card-class-name="planner-this-week-card" :on-open="props.onOpen" :on-drop="props.onDrop" /></section><section v-else-if="index === 5" class="board-this-week-weekend"><section v-for="weekend in days.slice(5)" :key="weekend.iso" class="board-this-week-day" :class="{ 'is-today': weekend.iso === today, [`day-${weekend.iso === days[5]?.iso ? 'sat' : 'sun'}`]: true }"><header class="board-this-week-day-header"><span class="board-this-week-day-title">{{ weekend.label }}</span><span class="board-this-week-day-date">{{ weekend.short }}</span><span v-if="weekend.iso === today" class="board-calendar-today-badge">Today</span></header><PlannerDropZone :date="weekend.iso" :entries="buckets.get(weekend.iso) || []" class-name="board-this-week-day-cards" group="planner-week-cards" card-class-name="planner-this-week-card" :on-open="props.onOpen" :on-drop="props.onDrop" /></section></section></template></div><div v-if="!buckets.size" class="planner-empty-state">No dated cards are visible this week. Add card or task start/due dates, or clear Planner filters.</div></section>
</template>
